name: Run Cypress on Browserstack
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: BrowserStack Local Tunnel Setup
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random

      - name: Install dependencies
        run: npm ci
      - name: Install Browserstack CLI
        run: npm install -g browserstack-cypress-cli
      - name: Build
        run: npm run build:lighthouse
      - name: Start web server
        run: npx http-server ./dist -p 1234 --cors &
      - name: Run Browserstack
        run: browserstack-cypress run

      - name: BrowserStackLocal Stop
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop